### ISSUE TITLE
cursr generates new configs on startup

### ISSUE THREAD

**Issue by SirBildigan** [bitgapp/Cursr#24] opened 2022-09-15 21:03 UTC
### Describe the Bug/Issue
On startup cursr generates new display configurations and selects it be default regardless of priority's set in other configurations

### Steps to Reproduce

1. Launch the app
2. see config is set to "Generated 2 new displays"

### Expected Behavior
I'd expect the configuration I have to be set on startup.

### Your Environment
 - OS details: Windows 10 64-bit (Build 19044.1889)
 - Cursr Version 1.4.9

### Additional Context
Sometimes it boots up properly, but mostly just generates new ones.

**Comment by ragauskl** [comment] 2022-09-15 23:04
@SirBildigan Is the issue happening in Free version or Pro version?

I'll try and resolve the issue in upcoming days, but it's possible that I won't be able to reproduce it as not too long ago there was a similar issue https://github.com/bitgapp/Cursr/issues/21 and after resolving that I had no issue with setup selection, in which case it would be helpful if you could send me logs from the app:

* go to settings > general and in there you'll find file icon next to Debug mode toggle
* click on it - it will open log files location
* enable the Debug mode (or leave it on if it was already on)
* close settings and replicate the issue, by relaunching app if needed
* send the log files to me at contact@cursr.app

**Comment by SirBildigan** [comment] 2022-09-15 23:56
alright, i sent over some log files to your email. also the version I am using is the pro version.

**Comment by ragauskl** [comment] 2022-09-16 00:02
Thank you, I'll let you know as soon as I'll find the issue/will know when I can make a release with the fix

**Comment by PsykomantaBrain** [comment] 2022-09-21 21:00
I've been having the same issue. Played around with the priorities, but it doens't seem to many any difference. I also tried to rename my profile with a leading underscore, so it sorts higher on the list, but that has no effect either.

**Comment by ragauskl** [comment] 2022-09-22 00:25
Good news, I have resolved the issue and will release the update tomorrow or day after (If I'll find anything else I can quickly include in the update so it's not just a single bug fix)

**Comment by ragauskl** [comment] 2022-09-24 00:49
Apologies for delay but it will take another day (worst case 2) as I'm finishing up highly requested 'auto enable/disable' feature testing and I remembered that there's still a bug to fix some people experience where app crashes on update restart

**Comment by ragauskl** [comment] 2022-09-26 07:37
@SirBildigan  @PsykomantaBrain Latest update is now live and issue with setup should be gone

**Comment by SirBildigan** [comment] 2022-09-28 18:44
So far it seems to be working flawlessly, hasn't failed to open up my config yet. the new feature for auto disable doesn't seem to work at all for me though.

**Comment by ragauskl** [comment] 2022-09-28 19:08
@SirBildigan Could I ask with what process/executable it's not working with? Did you add in settings which processes/executables should trigger Cursr disable when they're fullscreen and focused/active? Due to too many/inconsistent differences in 'fullscreen' modes based on applications I did not include a 'smart' auto detection, so while it's 'auto' disable, you still need to define for which processes

**Comment by SirBildigan** [comment] 2022-09-29 19:54
yeah, I added the paths for Halo infinite, Halo MCC, Fallout 4, Final Fantasy xii/xii-2, Skyrim Special edition, Scarlet Nexus, Tales of Arise. none of them would auto disable in either exclusive full screen or borderless.
![image](https://user-images.githubusercontent.com/113640095/193128997-2ac2a6a6-8363-43c8-ae82-231a3fe5ad81.png)

**Comment by ragauskl** [comment] 2022-09-29 20:35
Thanks, the setup look alright, only the .exe path is required

I'll test Cursr with mentioned games and see what might be wrong, as so far I only tested with League of Legends as it was mentioned first by other user and one other game I had

I'll close this issue and create a separate one for the auto disable bug

**Closed by ragauskl** 2022-09-29 20:35 UTC
Labels: bug

**Comment by ragauskl** [comment] 2022-11-03 22:33
@SirBildigan I've released version v1.4.11, if Cursr still does not auto disable when running games like Halo Infinite then could I ask you to enable Debug Mode in settings, and replicate the issue, then next to Debug Mode there is 'file' button, if you click it a folder will open - could you send the log files to me at contact@cursr.app , because I tried some of the mentioned games and it worked with all of them
