### ISSUE TITLE
Arrangement of displays don't line up

### ISSUE THREAD

**Issue by trapexit** [bitgapp/Cursr#5] opened 2021-07-17 17:39 UTC
### Describe the Bug/Issue

I've an eclectic setup. 4 1080p monitors all of different physical sizes. 1 4K. 1 1920x1200 tablet which runs Win 10 and is being used as monitor via Win10 projection. As can be seen in the attached image the layout doesn't ever seem to line up. It's unclear if that should matter but when attaching edges I can get seemingly buggy results.

### Expected Behavior

**Screenshots**

![image](https://user-images.githubusercontent.com/197676/126045257-0666c912-9596-44f7-a9d3-d4bbb41ab9c8.png)

### Your Environment
 - OS details: Win10 x86_64
 - Cursr Version: v1.2.0

**Comment by ragauskl** [comment] 2021-07-19 11:30
I'll take a look into this, but my testing setup is limited to 3 monitors, so it might be difficult to replicate this.

There has been an issue with underlying 3rd party library from which I am taking display information, where if display is rearranged in certain way, it returns incorrect positioning even if application is restarted. There is a quick way to fix this (if it's the same issue):

* In windows display arrangement settings, try to move screen 3 a bit to the left, like by couple pixels, apply changes, and then move it back where you want it and then apply changes again.

  Could you let me know if the above fixed the positioning in Cursr? If it did then it's known issue  on which I'm already working on, fix will be out in version 1.3.0 or 1.4.0.

If the above did not help, it will take more time, I will try to replicate it, but in case I can't get it to happen on my system I could send you a custom build with additional logging, you could then send me the logs bag and that should help me get an idea of why it's happening and how to solve it

**Comment by trapexit** [comment] 2021-07-21 22:41
Doesn't appear to have any impact. I did also notice though that when Cursr is showing where the mouse is it is off on screen 3 by what appears to be the offset that it thinks it is at. IE... it thinks it is left more than it is and when the mouse is actually all the way to the left on that monitor Cursr shows it as about half way.

**Comment by ragauskl** [comment] 2021-07-29 13:24
@trapexit  I managed to get some buggy behaviour as well when connecting mobile device as screen over spacedesk, so I have something to work with

![image](https://user-images.githubusercontent.com/9280160/127499397-3aa8999c-9137-487f-865d-83d348b543e9.png)
![image](https://user-images.githubusercontent.com/9280160/127499421-492b81e7-b850-4e23-832c-b1cda3a892ba.png)


I will try and fix it today, in which case it will be published with version 1.3.0 soon, I'll let you know when it's out and then we can see if this will hopefully fix the issue for you as well

**Comment by ragauskl** [comment] 2021-08-01 00:52
@trapexit Version 1.3.0 now available

The positioning should be fixed as I'm using native code to retrieve information (compared to using electron before, which had incorrect positions)

**Comment by ragauskl** [comment] 2021-08-01 12:50
There seems to be new issue which is a bit annoying, app keeps opening on startup, you can find workaround here https://github.com/bitgapp/Cursr/issues/6 while I find a fix for it

**Comment by trapexit** [comment] 2021-08-03 21:00
![cursr 1 3](https://user-images.githubusercontent.com/197676/128085412-9c09c142-5a90-4af5-be2c-023c585e8a33.png)

**Comment by ragauskl** [comment] 2021-08-03 22:45
huh... Okay I'll try and use win10 projection as you mentioned, because electron and same issue with using spacedesk is now out of question/fixed.  Currently I'm using just native windows library... I'll have a look tomorrow

**Comment by trapexit** [comment] 2021-08-03 23:42
* 1: 1080p builtin laptop screen
* 2: 4K connected to laptop gpu
* 3: 1080p connected to laptop gpu
* 4: 1080p connected via device hub with DisplayLink 
* 5: 1080p connected via same hub
* 6: 1920x1200 via Windows projection / Miracast

![image](https://user-images.githubusercontent.com/197676/128099652-726b0d63-2f5c-401e-9533-869e949e22b1.png)

I don't know if it is related but when I connected the left of 3 to the right of 4 in the setup with 5 monitors when I moved the mouse to 4 it immediately jumps to the left of 4 and when you try to move it right it freaks out and jumps back to the left.

**Comment by ragauskl** [comment] 2021-08-05 17:03
I tried various setups including using Windows projection and could not reproduce same issue, so it does not seem to be any specific issue with Win projection/Miracast, could be something to do with amount of displays but rather unlikely.

I'll create a custom build for you today with additional logging and send it over, I'll need you to reproduce both of the issues for the positioning and mouse movement and send the logs back (will send paths of logs with the build)

**Comment by ragauskl** [comment] 2021-08-05 18:11
I found some weird behaviour with 3rd party package when moving mouse to same position, it's not consistent, I'll fix that up and will send you build then, maybe it will improve/solve mouse issue on your end. Probably tomorrow or day after that

**Comment by ragauskl** [comment] 2021-08-06 13:42
@trapexit  I've added some minor changes and logs as mentioned:
[Cursr Installer](https://wormhole.app/WqjE4#cqx4nVVS831rDur1eBM0Hw) (Link available for 24h)

You can just download and run the installer, it will still say v1.3.1 and should preserve all current configurations.

Could you launch the app, reproduce the 2 bugs, and send me app.log file (if you didn't change default location during installation it should be in 'C:\Users\<user>\AppData\Roaming\cursr\Logs'). Ideally send the file to email contact@cursr.app or can also send over [wormhole.app](https://wormhole.app/) or similar

**Comment by ragauskl** [comment] 2021-08-19 02:44
@trapexit Did you have a chance to run the custom build with additional logging?

If not, then once you will, you'll need to go offline or in 'C:\Users\\\_user_\AppData\Roaming\cursr\conf.json' set 'autoUpdate' to 'false', as v1.3.2 is out now, to avoid auto update which will lose the additional logging and some native code changes in the build I've attached

**Comment by trapexit** [comment] 2021-08-19 02:48
Apologies. I've not gotten around to doing so. I'll try to do so tomorrow.

**Comment by ragauskl** [comment] 2021-08-25 01:08
@trapexit  Update, v1.3.3 is out now with 'debug mode' toggle in 'UI > Settings > General Settings'

You no longer need to download that custom build, just enable the 'debug mode' run the app for a bit/reproduce issues, and send me log files from 'C:\Users\\\_user_\AppData\Roaming\cursr\Logs' when you'll have a chance to do so

**Comment by ragauskl** [comment] 2021-11-29 03:37
There have been no more updates/comments on the issue, therefore it's  been fixed or is no longer relevant, therefore closing the issue. If anyone has this issue again, feel free to comment and reopen the issue.

**Closed by ragauskl** 2021-11-29 03:37 UTC
Labels: bug
