### ISSUE TITLE
I can't minimize the main screen. Minimize button doesn't work

### ISSUE THREAD

**Issue by chrisslyherin** [bitgapp/Cursr#3] opened 2021-07-13 17:55 UTC
### Macbook
 - Macbook air m1 - Big Sur 11.4
 - Cursr Version: 1.2.0

**Comment by ragauskl** [comment] 2021-08-01 00:50
@chrisslyherin Version 1.3.0 is out now, with it the issue should be gone

I could not reproduce the issue on Mac, but similar one was happening in versions <=1.1.0 so I added some logic to 'force' window hide, hopefully that will fix the issue for you

Could you let me know if it helped or not? I'll close the issue in 2 weeks time if there won't be any comments/complaints by that time

**Comment by ragauskl** [comment] 2021-08-19 02:46
Closing the issue as no further comments have been made after update/fix

**Closed by ragauskl** 2021-08-19 02:46 UTC
Labels: bug
