### ISSUE TITLE
Vertical to Horizontal mapping is incorrect for monitor on the left

### ISSUE THREAD

**Issue by gjobin** [bitgapp/Cursr#44] opened 2023-06-01 17:13 UTC
### Describe the Bug/Issue
The cursor is not going to the expected location when the monitor is on the left and there is a bound across vertical and horizontal borders.

### Steps to Reproduce

1. Set a border to match vertical on one screen below the other, and horizontal on screen to is on the left.
2. Move mouse across that boundary, the mapping is reversed.

![image](https://github.com/bitgapp/Cursr/assets/9118970/b4015621-5f9a-4c96-9061-7af889bd0c63)

### Expected Behavior
I would expect the mapping to behave the same way in relation to the screen when it is on the left.
![image](https://github.com/bitgapp/Cursr/assets/9118970/c41a1048-1357-4de9-881c-00e569619462)

### Your Environment
 - OS details: MAC Ventura 13.4
 - Cursr Version: 1.4.13 Mac arm64
 - License: [e.g. Pro/Free] Pro

### Additional Context

It works as expected if the screen is on the right.

**Comment by ragauskl** [comment] 2023-06-01 17:50
@gjobin yeah I'm aware of this one, technically it's not a bug but a bad user experience as Cursr is mapping positions from lowest coordinate to highest (on coordinate system top to bottom and left to right so it's consistent across different systems)

I just never got to adding extra piece of code to add option to invert it and to invert by default in the case you mentioned, but it is still in the to do list to be done as soon as I'm done with stable KVM version

**Comment by gjobin** [comment] 2023-06-01 18:10
@ragauskl thanks for confirming the issue is known an d planned to be worked on.
I would still consider the lack of option to invert the reference as a bug though, as it does not allow the configuration to make it work as expected (intended?).

I am however with you on the fact that inverting by default could be considered as a nice to have / feature request.

Is there any chance the option to invert be implemented sooner rather than later ?
Is there an ETA for stable KVM version ?

Thank you, appreciate your work, and that's why I wanted to purchase the Pro version to support it.
Good thing I did, as it allowed me to split the issue across multiple zones to reduce the bad effect as a workaround

![image](https://github.com/bitgapp/Cursr/assets/9118970/44802655-bb03-4f43-9188-c3e40fb4170f)

**Comment by ragauskl** [comment] 2023-06-01 19:13
That's a creative solution 😄

So I was hoping to make stable release before 8 May as I was leaving on long overdue holiday, but decided I'll just make an update to KVM Beta and will try to get more beta testers participating as so far there's still under 20 people and only under 10 provided any feedback. During my time off I prioritise any critical issues like one's with payments and licenses, and any tasks where I don't need to spend too much time by computer (like looking for more beta testers or planning) 

I will be coming back sometime mid June and will resume fulltime work on Cursr, I'll probably spend couple more weeks polishing off Beta and if no major issues popup will release it start of July. But it's hard for me to promise anything 100% as I'm working alone on it so any other tasks work or life that popup halt/delay everything else unfortunately.

But I am focusing on getting KVM basic stable version out as soon as I can and then focus on any issues or annoyances with using Cursr, so rest assured this task is of high priority/near top of the list

**Comment by gjobin** [comment] 2023-06-02 14:05
Tank you very much for the update. I totally understand the situation you're in and gotta prioritize.
Appreciate the feedback and looking forward for updates. Enjoy your time off.

**Comment by ragauskl** [comment] 2023-08-02 23:13
@gjobin Closing the issue as the requested change has been added in v1.5.0 which is now live, borders bottom <> left and right <> top will be inverted by default for more expected/natural behavior, users can change this in the segments panel per individual link. The segments panel is currently only available in Pro version, but border inversion is not paid feature, I just need a bit more time to create a 'free' version of the panel so it will be coming out in future

**Closed by ragauskl** 2023-08-02 23:13 UTC

**Comment by gjobin** [comment] 2023-08-04 17:18
@ragauskl Thank you very much. Working as expected. 🎉
