### ISSUE TITLE
unexpected error with upgrade

### ISSUE THREAD

**Issue by ltd** [bitgapp/Cursr#7] opened 2021-08-03 17:34 UTC
### Describe the Bug/Issue
Restarted the app, and now get an "unexpected error" message and no screens, I will uninstall and try a fresh install

### Steps to Reproduce

1. restart the app from 1.2.0

### Expected Behavior

**Screenshots**
<img width="647" alt="Cursr_and_bitgapp_Cursr__Public_repository_for_Cursr_releases_and_discussion_bug_reports" src="https://user-images.githubusercontent.com/67152/128060224-82974166-026a-44af-a240-eab5c2a22d68.png">

### Your Environment
 -macos
 - Cursr Version 1.30

**Comment by ragauskl** [comment] 2021-08-03 23:57
Sorry for the inconvenience

I just tried to update on 2 different Macs and could not get the issue to appear, could you attach here (or send me to email contact@cursr.app ) error log file, should be located in '~/Library/Application Support/cursr/Logs/error.log'

**Comment by ragauskl** [comment] 2021-08-04 00:07
And could you also let me know what version of macos you're using and if by any chance your device uses M1 chip? Application now get's display information from native libraries rather than depending on 3rd party due to previous issues, I have a guess there could be a compatibility issue (fixable) with older macos versions or if it runs on M1 chip

**Comment by ltd** [comment] 2021-08-04 08:13
I'm on an intel mac, latest os updates
uname -a
Darwin mbp16.local 20.6.0 Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:31 PDT 2021; root:xnu-7195.141.2~5/RELEASE_X86_64 x86_64


2021-07-19T05:04:38.988Z [error] net::ERR_NETWORK_CHANGED Error: net::ERR_NETWORK_CHANGED
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105:7068)
    at SimpleURLLoaderWrapper.emit (events.js:315:20)
2021-08-03T17:28:47.323Z [critical] RangeError: Invalid array length
    at Edid.parseAudioDataBlock (/Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/dist/edid/edid-parser.js:737:23)
    at Edid.parseDataBlockCollection (/Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/dist/edid/edid-parser.js:701:30)
    at Edid.parse (/Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/dist/edid/edid-parser.js:222:60)
    at Function.parse (/Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/dist/edid/index.js:93:20)
    at /Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/dist/edid/index.js:72:44
    at arrayMap (/Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/node_modules/lodash/lodash.js:653:23)
    at Function.map (/Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/node_modules/lodash/lodash.js:9622:14)
    at /Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/dist/edid/index.js:71:31
    at tryCatcher (/Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/node_modules/bluebird/js/release/promise.js:729:18)
    at Promise._fulfill (/Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/node_modules/bluebird/js/release/promise.js:673:18)
    at MappingPromiseArray.PromiseArray._resolve (/Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/node_modules/bluebird/js/release/promise_array.js:127:19)
    at MappingPromiseArray._promiseFulfilled (/Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/node_modules/bluebird/js/release/map.js:108:18)
2021-08-03T17:29:41.100Z [critical] RangeError: Invalid array length
    at Edid.parseAudioDataBlock (/Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/dist/edid/edid-parser.js:737:23)
    at Edid.parseDataBlockCollection (/Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/dist/edid/edid-parser.js:701:30)
    at Edid.parse (/Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/dist/edid/edid-parser.js:222:60)
    at Function.parse (/Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/dist/edid/index.js:93:20)
    at /Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/dist/edid/index.js:72:44
    at arrayMap (/Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/node_modules/lodash/lodash.js:653:23)
    at Function.map (/Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/node_modules/lodash/lodash.js:9622:14)
    at /Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/dist/edid/index.js:71:31
    at tryCatcher (/Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/node_modules/bluebird/js/release/promise.js:729:18)
    at Promise._fulfill (/Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/node_modules/bluebird/js/release/promise.js:673:18)
    at MappingPromiseArray.PromiseArray._resolve (/Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/node_modules/bluebird/js/release/promise_array.js:127:19)
    at MappingPromiseArray._promiseFulfilled (/Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/node_modules/bluebird/js/release/map.js:108:18)
2021-08-03T17:30:32.889Z [critical] RangeError: Invalid array length
    at Edid.parseAudioDataBlock (/Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/dist/edid/edid-parser.js:737:23)
    at Edid.parseDataBlockCollection (/Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/dist/edid/edid-parser.js:701:30)
    at Edid.parse (/Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/dist/edid/edid-parser.js:222:60)
    at Function.parse (/Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/dist/edid/index.js:93:20)
    at /Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/dist/edid/index.js:72:44
    at arrayMap (/Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/node_modules/lodash/lodash.js:653:23)
    at Function.map (/Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/node_modules/lodash/lodash.js:9622:14)
    at /Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/dist/edid/index.js:71:31
    at tryCatcher (/Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/node_modules/bluebird/js/release/promise.js:729:18)
    at Promise._fulfill (/Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/node_modules/bluebird/js/release/promise.js:673:18)
    at MappingPromiseArray.PromiseArray._resolve (/Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/node_modules/bluebird/js/release/promise_array.js:127:19)
    at MappingPromiseArray._promiseFulfilled (/Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/node_modules/bluebird/js/release/map.js:108:18)
2021-08-03T17:34:31.498Z [critical] RangeError: Invalid array length
    at Edid.parseAudioDataBlock (/Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/dist/edid/edid-parser.js:737:23)
    at Edid.parseDataBlockCollection (/Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/dist/edid/edid-parser.js:701:30)
    at Edid.parse (/Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/dist/edid/edid-parser.js:222:60)
    at Function.parse (/Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/dist/edid/index.js:93:20)
    at /Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/dist/edid/index.js:72:44
    at arrayMap (/Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/node_modules/lodash/lodash.js:653:23)
    at Function.map (/Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/node_modules/lodash/lodash.js:9622:14)
    at /Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/dist/edid/index.js:71:31
    at tryCatcher (/Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/node_modules/bluebird/js/release/promise.js:729:18)
    at Promise._fulfill (/Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/node_modules/bluebird/js/release/promise.js:673:18)
    at MappingPromiseArray.PromiseArray._resolve (/Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/node_modules/bluebird/js/release/promise_array.js:127:19)
    at MappingPromiseArray._promiseFulfilled (/Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/node_modules/bluebird/js/release/map.js:108:18)
2021-08-03T17:36:02.544Z [critical] RangeError: Invalid array length
    at Edid.parseAudioDataBlock (/Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/dist/edid/edid-parser.js:737:23)
    at Edid.parseDataBlockCollection (/Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/dist/edid/edid-parser.js:701:30)
    at Edid.parse (/Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/dist/edid/edid-parser.js:222:60)
    at Function.parse (/Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/dist/edid/index.js:93:20)
    at /Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/dist/edid/index.js:72:44
    at arrayMap (/Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/node_modules/lodash/lodash.js:653:23)
    at Function.map (/Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/node_modules/lodash/lodash.js:9622:14)
    at /Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/dist/edid/index.js:71:31
    at tryCatcher (/Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/node_modules/bluebird/js/release/promise.js:729:18)
    at Promise._fulfill (/Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/node_modules/bluebird/js/release/promise.js:673:18)
    at MappingPromiseArray.PromiseArray._resolve (/Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/node_modules/bluebird/js/release/promise_array.js:127:19)
    at MappingPromiseArray._promiseFulfilled (/Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/node_modules/bluebird/js/release/map.js:108:18)
2021-08-03T17:37:34.252Z [critical] RangeError: Invalid array length
    at Edid.parseAudioDataBlock (/Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/dist/edid/edid-parser.js:737:23)
    at Edid.parseDataBlockCollection (/Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/dist/edid/edid-parser.js:701:30)
    at Edid.parse (/Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/dist/edid/edid-parser.js:222:60)
    at Function.parse (/Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/dist/edid/index.js:93:20)
    at /Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/dist/edid/index.js:72:44
    at arrayMap (/Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/node_modules/lodash/lodash.js:653:23)
    at Function.map (/Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/node_modules/lodash/lodash.js:9622:14)
    at /Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/dist/edid/index.js:71:31
    at tryCatcher (/Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/node_modules/bluebird/js/release/promise.js:729:18)
    at Promise._fulfill (/Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/node_modules/bluebird/js/release/promise.js:673:18)
    at MappingPromiseArray.PromiseArray._resolve (/Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/node_modules/bluebird/js/release/promise_array.js:127:19)
    at MappingPromiseArray._promiseFulfilled (/Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/node_modules/bluebird/js/release/map.js:108:18)
2021-08-03T23:02:36.346Z [critical] RangeError: Invalid array length
    at Edid.parseAudioDataBlock (/Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/dist/edid/edid-parser.js:737:23)
    at Edid.parseDataBlockCollection (/Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/dist/edid/edid-parser.js:701:30)
    at Edid.parse (/Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/dist/edid/edid-parser.js:222:60)
    at Function.parse (/Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/dist/edid/index.js:93:20)
    at /Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/dist/edid/index.js:72:44
    at arrayMap (/Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/node_modules/lodash/lodash.js:653:23)
    at Function.map (/Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/node_modules/lodash/lodash.js:9622:14)
    at /Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/dist/edid/index.js:71:31
    at tryCatcher (/Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/node_modules/bluebird/js/release/promise.js:729:18)
    at Promise._fulfill (/Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/node_modules/bluebird/js/release/promise.js:673:18)
    at MappingPromiseArray.PromiseArray._resolve (/Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/node_modules/bluebird/js/release/promise_array.js:127:19)
    at MappingPromiseArray._promiseFulfilled (/Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/node_modules/bluebird/js/release/map.js:108:18)
2021-08-04T07:38:37.276Z [critical] RangeError: Invalid array length
    at Edid.parseAudioDataBlock (/Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/dist/edid/edid-parser.js:737:23)
    at Edid.parseDataBlockCollection (/Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/dist/edid/edid-parser.js:701:30)
    at Edid.parse (/Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/dist/edid/edid-parser.js:222:60)
    at Function.parse (/Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/dist/edid/index.js:93:20)
    at /Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/dist/edid/index.js:72:44
    at arrayMap (/Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/node_modules/lodash/lodash.js:653:23)
    at Function.map (/Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/node_modules/lodash/lodash.js:9622:14)
    at /Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/dist/edid/index.js:71:31
    at tryCatcher (/Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/node_modules/bluebird/js/release/promise.js:729:18)
    at Promise._fulfill (/Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/node_modules/bluebird/js/release/promise.js:673:18)
    at MappingPromiseArray.PromiseArray._resolve (/Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/node_modules/bluebird/js/release/promise_array.js:127:19)
    at MappingPromiseArray._promiseFulfilled (/Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/node_modules/bluebird/js/release/map.js:108:18)

**Comment by ragauskl** [comment] 2021-08-04 11:13
Okay I see where the issue is, I'll release an update today

**Comment by ragauskl** [comment] 2021-08-05 02:53
@ltd Should be fixed now! v1.3.1

**Comment by ragauskl** [comment] 2021-08-06 17:42
Closing as there were no further comments about the issue

**Closed by ragauskl** 2021-08-06 17:42 UTC
