### ISSUE TITLE
Deadzones in passable Link Borders

### ISSUE THREAD

**Issue by SirBildigan** [bitgapp/Cursr#48] opened 2023-11-29 21:54 UTC
### Describe the Bug/Issue
I have an issue that has started in version 1.6.2 and 1.6.3. Whenever i try to pass my mouse through a link border that is super close to a dead zone if my mouse just happens to touch a deadzone by even 1 px the rest of the link borders will become unpassable upto my monitors native link borders.

### Steps to Reproduce

1. Go to 
'any deadzone thats near a link border and touch it while trying to then move through a linked border'

### Expected Behavior
it should pass through cursr's linked borders
**Screenshots**
See video. starts out showing how it should passthrough and then shows how it wont if i hit a deadzone first
https://github.com/bitgapp/Cursr/assets/113640095/97ba9038-63d8-47b9-93c0-b2322ce44ff8

### Your Environment
 - OS details: [Windows 11 x64]
 - Cursr Version: [e.g. 1.6.3]
 - License: [ Pro ]

### Additional Context
i have a 32' 1440p monitor next to a 27' 1080p monitor. this issue is common on this setup because i need to move diagonally at times to reach other monitor so its not uncommon to hit a deadzone first

**Comment by ragauskl** [comment] 2023-11-29 23:24
Thanks for bringing that to my attention, it looks like it will be easy to reproduce and likely also easy to fix

Expect a fix in v1.6.4, but can't promise a time as I'm currently in progress of moving to/settling in a new home and won't be able to resume work for at least couple more days, but once settled in I'll try to release v1.6.4 with some accumulated issues fixed within a week or two

I

**Comment by ragauskl** [comment] 2023-12-22 01:55
Resolved in 1.6.4

**Closed by ragauskl** 2023-12-22 01:55 UTC
Labels: bug
