### ISSUE TITLE
Setup gets reset after each update

### ISSUE THREAD

**Issue by ArtemisMalak** [bitgapp/Cursr#49] opened 2023-12-22 23:54 UTC
Hello. I wanted to report a bug where after each time Cursr is updated, my Setup for my monitors gets reset and the setup I created is gone. I have to redo my setup every time the app gets updated.

**Comment by ragauskl** [comment] 2023-12-23 00:35
Hey, what OS are you using? Is it macOS by any chance?

**Comment by ArtemisMalak** [comment] 2023-12-23 13:05
> Hey, what OS are you using? Is it macOS by any chance?

I’m using Windows 11.

**Comment by roberthuang0306** [comment] 2023-12-31 15:31
I'm using MacOS and encounter the same problem.
It will randomly been reset after restart.

**Comment by ragauskl** [comment] 2024-01-01 03:54
I will be looking into fixing this for next patch or minor update whichever will come first.

I've also encountered this issue but only in development environment and could not replicate it in production and hoped it was specific to development, but as it's affecting multiple users it's a priority fix

**Comment by ArtemisMalak** [comment] 2024-01-01 13:25
Thank you! I’ll keep an eye out for the update.

**Comment by ragauskl** [comment] 2024-01-04 18:00
I've included a fix in 1.6.5 which is now live, I can no  longer replicate the issue on my end. Let me know if the issue still persists, otherwise I'll close this in couple of weeks if there won't be any new comments

**Comment by ArtemisMalak** [comment] 2024-01-06 13:12
Looks okay so far, but I may not know until the next update. I think my install got corrupted and it wouldn’t update itself. I had to uninstall the app completely and reinstall the new version.

**Comment by ragauskl** [comment] 2024-01-06 16:47
@ArtemisMalak That's fine, if issue repeats you can always re-open this one or a new issue, but if it didn't happen now I think it won't happen on next update as I've fixed very specific issue that was causing the configuration reset so I'm pretty confident it should be gone.

In terms of install being corrupt - if you've updated from version 1.6.1 or lower this will be due to signing certificate issue that happened, I've mentioned it on Discord so anyone not on discord would have not known - what happened was that 'code signing certificate' I use on Windows comes from ssl.com which introduced list of changes to their system in summer I think and when I had to renew certificates for some reason they generated the company name of certificate owner from 'Bitgapp Ltd.' to 'Bitgapp Ltd' by removing the dot - this causes the update to think that  certificate now belongs to a different publisher/company causing the update to fail. I only realised it's an issue when update was released so I stick with the new certificate and will know to keep an eye on this on every certificate renewal going forward.

**Comment by ragauskl** [comment] 2024-01-06 16:50
@roberthuang0306 after you use the latest update 1.6.5 for some time - I'd be really grateful if you'd let me know if the issue is still occurring or not after a restart

**Comment by ragauskl** [comment] 2024-02-04 16:25
Closing the issue as there was another release and there were no reports of the issue reoccurring

**Closed by ragauskl** 2024-02-04 16:25 UTC
Labels: bug
