### ISSUE TITLE
Remember settings

### ISSUE THREAD

**Issue by janosdre** [bitgapp/Cursr#1] opened 2021-06-22 12:53 UTC
The application does not seem to remember the settings. So when I go back to my desk, I have to set up the transitions again. It would be great if Cursr remembered the monitor and settings.

**Comment by ragauskl** [comment] 2021-06-22 14:13
Currently Cursr should remember settings as long as the desktop setup does not change, both on restart and after sleep.  If you did not change desktop setup and settings still did not stay saved, then it would be useful to know what Operating System you have and get a screenshot of Cursr application running on your system, also does it happen after restart/shutdown or sleep? if needed I might ask for more details, like logs later.

If you did change - It is near the top of to-do list to implement better settings saving, so that settings can be saved for different setups, with auto detect of which setup should be loaded, so settings will then be remembered even when display setup is changed. 

What makes it a bit tricky is that displays don't always have same ID with the libraries currently in use, so they can have a new ID on next startup or don't have one at all, leaving options to look into other libraries or do detection based on screen measurements, but that has plenty of edge cases to take care off, therefore I it's more time taking to solve and I left it out from the initial release

**Comment by ragauskl** [comment] 2021-07-01 09:17
@janosdre Quick update, fix will be coming out in release 1.3.0, approximately in 1 weeks time

**Comment by ragauskl** [comment] 2021-08-01 00:46
@janosdre Sorry for the delay, my schedule turned upside down, but the version 1.3.0 is out now

Application should now remember settings consistently, and also it will allow you to save different setups you've made, it will also generate new setups if matching one was not found based on connected displays

Could you let me know when you have a chance to check it out and see if it now works for you as expected? I'll keep this issue open for 2 weeks and if there is no response/complaints I'll close the issue

**Comment by ragauskl** [comment] 2021-08-19 02:46
Closing the issue as no further comments have been made after update/fix

**Comment by shipitsteven** [comment] 2021-09-12 18:09
Having the same issue on `1.3.3`. Launch on Startup setting is not being saved after restarting/quitting the app/shut down. Auto update & Debug are saved though.

**Comment by ragauskl** [comment] 2021-09-13 12:44
@shipitsteven Which OS are you using?

Issue you mention is a bit different from original, which was about mouse transition/border link setup/configuration saving, but I'll keep it under this one as people with either issue will likely look here

**Comment by ragauskl** [comment] 2021-09-13 14:16
Also could I ask you to double check that if you enable 'launch on startup' now in v1.3.3 and after restart/shut down it's working or not

Asking to double check because I cannot replicate same issue on restart/shut down alone, however I did notice that after app reload due to update - it does get disabled on Windows (haven't checked others yet), for which I'll release a fix shortly

**Comment by shipitsteven** [comment] 2021-09-14 00:12
> Which OS are you using?

Windows 10

> Issue you mention is a bit different from original, which was about mouse transition/border link setup/configuration saving

That part is indeed working. Border link setup are saved on restart/quit/shut down on my end

I tried it again today, same issue. Launch on Startup option doesn't get saved on app quit/restart. Thanks for looking into it 🤓🙏🏻

**Comment by ragauskl** [comment] 2021-09-14 20:00
Could I ask you to install [v1.3.4 pre-release](https://drive.google.com/file/d/1ovb5yl920FKlOWY25UxRMhpnU5B-oeuD/view?usp=sharing) and see if that works? 

If it won't still work then:
* in case it fails to even set 'launch at startup' you will see in-app error notification
* if it won't means issue will be with reigstry entry for launching app on startup getting deleted or disabled

In either case if it does not work I'll ask you to:
*  enable 'Debug mode' from settings
*  enable 'Launch on startup'
*  restart computer
*  open Cursr again 
*  send me logs 'app.log' and 'error.log' from 'C:\Users\\\_user_\AppData\Roaming\cursr\Logs' (if installation path was not changed) to contact@cursr.app

**Comment by ragauskl** [comment] 2021-09-20 17:24
@shipitsteven I've released new version with some updates/fixes but it's likely it won't fix issue you were having as I cannot reproduce it and test it/have no information on why it's happening.

If the issue still exists for you after update could I ask you to do the steps mentioned in comment above and send me the logs, that would hopefully let me get better idea of what could be causing the issue

**Comment by ragauskl** [comment] 2021-10-16 11:13
@shipitsteven I've released v1.3.5 with a fix, could you let me know if it works as expected now?

**Comment by ragauskl** [comment] 2021-11-29 03:52
There have been no more updates/comments on the issue for a while, therefore it's been fixed or is no longer relevant, therefore closing the issue. If anyone has this issue again, feel free to comment and reopen the issue.

**Closed by ragauskl** 2021-11-29 03:52 UTC
Labels: bug, enhancement
