### ISSUE TITLE
Cursr doesn't seem to respect Setup priorities

### ISSUE THREAD

**Issue by marcaddeo** [bitgapp/Cursr#21] opened 2022-07-20 15:50 UTC
### Describe the Bug/Issue

When Cursr starts, sometimes (always? I'm unsure), it seems to generate a new Setup and then use that over my pre-defined setup. I've set the priority of my custom setup to `10000`, but it still doesn't seem to get selected.

I have a suspicion that this is related to not getting the license validated in time.

### Steps to Reproduce

1. Open application
2. A 'Generated - 3 Displays' is created with the default priority of `10`
3. My custom setup with a priority of `10000` is ignored.

### Expected Behavior

I expect my high priority setup to be selected and used every time the application launches

### Your Environment
 - OS details: macOS 12.4
 - Cursr Version: v1.4.5

**Comment by ragauskl** [comment] 2022-07-20 16:03
The priority/order selects lower number over higher

 I've just double checked with couple people what they would think is order of priority and all answered that 1 is higher priority than 10, jist like it is now

But if you have reason why it should be otherwise let me know, I might be missing something 

But if you have a setup created it shouldn't try to create new setup, that would be a bug, is it actually creating new setup (adding new entry in setups list) or is it just selecting previously generated setup (in which case its just order adjustment thing/not a bug)

**Comment by marcaddeo** [comment] 2022-07-20 16:06
> The priority/order selects lower number over higher
> 
> I've just double checked with couple people what they would think is order of priority and all answered that 1 is higher priority than 10, jist like it is now
> 
> But if you have reason why it should be otherwise let me know, I might be missing something
> 
> But if you have a setup created it shouldn't try to create new setup, that would be a bug, is it actually creating new setup (adding new entry in setups list) or is it just selecting previously generated setup (in which case its just order adjustment thing/not a bug)

D'oh. Guess that's just my stupid brain not getting priority order correct.

Anyway, I just set my custom Setup to priority `1` and _deleted_ the generated one then quit the app.

When I reopened the app, there was a new generated setup and it was active instead of my priority `1` setup.

**Comment by ragauskl** [comment] 2022-07-20 16:07
Well I guess i have additional work then 😅 I'll have it checked out soon and will release an update

**Comment by ragauskl** [comment] 2022-07-22 22:06
I think I resolved the issue, logic to wait for license to get loaded was already in place, I think issue was related to the fact that I added logic where if a setup is selected and additional display get's added, if possible Cursr preserves the setup selection instead of creating new one which is useful in some cases, but in this case due to sequence of events that could potentially happen (but I couldn't replicate it) Cursr thought it had new 'layout' , created a setup for it, and then when all display data was correctly loaded it preserved that setup instead of selecting the one you want.

It will still do this if priority numbers are the same, however if you set priority it will now select the higher priority setup as it should

I still want to do some additional testing to check for anything else I might've missed before releasing an update, to avoid making one too often, and I have some plans tomorrow I can't postpone, so I will complete testing and make a release late tomorrow or day after so in 24-48 hours

**Comment by ragauskl** [comment] 2022-07-24 16:42
@marcaddeo It should now be working as expected in release v1.4.6, let me know if the issue has been resolved or is it still happening after update

**Comment by marcaddeo** [comment] 2022-07-25 14:23
@ragauskl thanks for the quick fixes.

I quit and reopened a bunch of times, and it seems to be mostly solved. However like the 5th time I reopened it, it generated a new setup and it took priority over my own.

**Comment by ragauskl** [comment] 2022-07-25 21:13
Okay I see, could I ask you to

* go to settings > general and in there you'll find file icon next to Debug mode toggle
* click on it - it will open log files location
* delete all the files in there
* enable the Debug mode (or leave it on if it was already on)
* close settings and replicate the issue, by relaunching app if needed
* send the log files to me at contact@cursr.app

I'll be able to better investigate the issue then and understand what exactly happens in your case because I can't replicate it locally

**Comment by ragauskl** [comment] 2022-08-12 18:35
@marcaddeo I've just released v1.4.9, issue should be fully resolved now

**Comment by ragauskl** [comment] 2022-09-13 18:07
Closing the issue as there were no more comments about the issue after update mentioned above

**Closed by ragauskl** 2022-09-13 18:07 UTC
